apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: app-container
          image: {{ .Values.application.image }}
          ports:
            - containerPort: {{ .Values.application.port }}
        - name: db-container
          image: {{ .Values.database.image }}
          ports:
            - containerPort: {{ .Values.database.port }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"